name: Documentation
description: Improvements or additions to documentation
labels: ["type:docs"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: textarea
    id: description
    attributes:
      label: What needs to be documented?
      description: Describe what documentation is missing, incorrect, or could be improved.
      placeholder: The README doesn't explain how to...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where should this documentation live? (file path, section, etc.)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or examples.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this documentation?
      options:
        - "priority:low - Address when time permits"
        - "priority:medium - Normal workflow"
        - "priority:high - Should be addressed soon"
        - "priority:critical - Requires immediate attention"
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How much effort do you think this will take?
      options:
        - "size:xs - Trivial change, <1 hour"
        - "size:s - Simple change, 1-4 hours"
        - "size:m - Moderate effort, 1-2 days"
        - "size:l - Significant work, 3-5 days"
        - "size:xl - Major effort, 1+ weeks"
    validations:
      required: true
